name: sync-and-dump-s3 # you probably want to 'snapcraft register <name>'
version: '0.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: Sync aws s3 buckets and Upload dumps of mysql and mongodb # 79 char long summary
description: |
  So tired of clicking and writing a pile of on the cli to sync your buckets on aws S3?
  Or do you just want your dumps to reach aws S3 faster?
  With a support for mongodb and mysql, the SyncAndDumpS3 does exactly that for you!*
  Automate and don't wait!

  (**Needs mysql or mongodb installed on your host machine or server)

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures: [ all ]

apps:
  sync-and-dump-s3:
    command: bash syncScript.sh

    

parts:
  sync-and-dump-s3:
    plugin: nil
    source: https://github.com/ScorchingShade/SyncAndDumpS3.git
    
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp syncScript.sh $SNAPCRAFT_PART_INSTALL/bin/
    